name       : python-pysmbc
version    : 1.0.24
release    : 31
source     :
    - https://files.pythonhosted.org/packages/source/p/pysmbc/pysmbc-1.0.24.tar.gz : ceade8d611e63d72a75d262b342a6dc836b6f80ab38ea5fd5ad443e2f7be2ced
homepage   : https://github.com/hamano/pysmbc
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python bindings for libsmbclient from the Samba project
description: |
    This package provides Python bindings for the libsmbclient API from Samba, known as pysmbc. It was written for use with system-config-printer, but can be put to other uses as well.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(smbclient)
setup      : |
    %python3_setup
install    : |
    %python3_install
