name       : python-pysmbc
version    : 1.0.15.8
release    : 23
source     :
    - https://pypi.python.org/packages/44/6b/02724b54de3543718ccc6ac841ce0c17aa9851b3e77162d70f7d78edff2a/pysmbc-1.0.15.8.tar.bz2 : 0567c1789a911500b83c64becdaa0015c135cce0bcf59ec593df48859bebbf1d
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python bindings for libsmbclient from the Samba project
description: |
    This package provides Python bindings for the libsmbclient API
    from Samba, known as pysmbc. It was written for use with
    system-config-printer, but can be put to other uses as well.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(smbclient)
setup      : |
    %python3_setup
install    : |
    %python3_install
